name: Build and deploy Python and Vue.js app to Azure Web App - IDP-insurance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Setup Python (Backend)
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and Start virtual environment and Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
      # Setup Node.js (Frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Menentukan versi Node.js yang dibutuhkan oleh Vue.js

      - name: Install dependencies for Vue.js
        run: |
          cd frontend  # Menyesuaikan dengan direktori tempat aplikasi Vue.js berada
          npm install
      # Upload artifact for deployment jobs
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-vue-app
          path: |
            .
            !antenv/
            !frontend/node_modules/  # Menghindari upload node_modules
            frontend/dist/  # Folder hasil build Vue.js
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-vue-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'IDP-insurance'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8D12BD34FC064BCD98CD66A73C512DBD }}
